# Generated by Django 4.2.4 on 2023-09-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indomie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField(default=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=2500)),
                ('type', models.CharField(choices=[('MG', 'Mie Goreng'), ('MK', 'Mie Kuah'), ('MJ', 'Mie Jumbo'), ('SN', 'Selera Nusantara'), ('HA', 'Hype Abis')], max_length=2)),
            ],
        ),
    ]
